### ISSUE TITLE
Website peer review

### ISSUE THREAD

**Issue by harveenn** [OIM3690/WebTech#1]
First of all, I think you have a really cool topic. I really like cars too and I love how you home page looks. I think you can add more to that by using the javascript we are now learning to make smoother transitions between pages with the "continue tour" button. I also really like your navigation bar but I feel like you can do more with it, like put it on the side maybe because there is a lot of empty space on you main content pages and you might want to fill that up. 

For your code, I noticed that you have used external CSS. It might help to have everything on the same page. I don't see any issues with it but I feel like if the code was lengthier, you could face an issue with it. But as of right now it seems to be working great for you! I would suggest try and adding some icons to your page to give it a bit more life and maybe cover the empty spaces a bit. Other than that I feel you have created an amazing website!

**Comment by lzblack** [comment]
Please create issue in the correct repository.
