### ISSUE TITLE
What is the name for this --> " + const name + "

### ISSUE THREAD

**Issue by xjiang1** [OIM3690/WebTech#2]
In quiz 3-2, we used to change part of the text, so we used " + x + " to change the value. I searched on Google by using keywords "javascript "+ +" ", but I didn't find anything about this. What is the name of this? And what keywords should I use to search about it if I want to learn more.

**Comment by lzblack** [comment]
I guess you want to search "javascript concatenate strings"?

**Comment by xjiang1** [comment]
> 

Thank you very much!!
